stages:
    - test
    - lint

unit-test:
    stage: test
    tags:
        - docker
    image: "python:latest"
    script:
        - python -m pip install --upgrade pip
        - pip install -r requirements.txt
        - python -m pytest --cov-report=html --cov=src .
        - coverage report --omit=venv/*
    coverage: '/TOTAL.*\s+(\d+\%)/'
    artifacts:
        paths:
            - coverage
        expire_in: 30 days

lint:
    stage: lint
    tags:
        - docker
    image: "python:latest"
    allow_failure: true
    script:
        - pip install -r requirements.txt
        - pylint src/
