stages:
    - test
    - lint

unit-test:
    stage: test
    tags:
        - docker
    image: "python:latest"
    script:
        - pip install pytest pytest-cov
        - python -m pytest --cov-report=html --cov=src .
        - python -m pytest --cov=sh16-main tests/
    artifacts:
        paths:
            - coverage
        expire_in: 30 days

lint:
    stage: lint
    tags:
        - docker
    image: "python:latest"
    allow_failure: true
    script:
        - pip install pylint
        - pylint src/
