stages:
    - test

unit-test:
    stage: test
    tags:
        - docker
    image: python:3.10
    script:
        - pip install pytest pytest-cov
        - python -m pytest --cov-report=html --cov=src .
    artifacts:
        paths:
            - coverage
        expire_in: 30 days
